### ISSUE TITLE
Cannot play videos

### ISSUE THREAD

**Issue by ondrik** [willforde/plugin.video.watchmojo#1]
Dear author,

I've recently encountered an error when using the watchmojo plugin on kodi. When I wish to play a video, it doesn't start, instead, I get the error "Unexpected error. An Unexpected error occured." (and sometimes a messagebox "Playback failed. One or more items failed to play. Check the log for more information about this message." I'm using the plugin in version 2.10.0 on Kodi 17 (LibreELEC 8.0.0).
An excerpt from the log:

```
21:37:12.016 T:1674679200  NOTICE: [plugin.video.watchmojo] http://www.watchmojo.com
21:37:12.016 T:1674679200    NONE: [plugin.video.watchmojo] UrlHash = 01b6e4fa8df33559ca8dd6df44d8e055
21:37:12.021 T:1674679200  NOTICE: [plugin.video.watchmojo] Cached
21:37:12.025 T:1674679200    NONE: [plugin.video.watchmojo] 200 - OK
21:37:12.667 T:1674679200    NONE: [plugin.video.watchmojo] [10]
21:37:15.180 T:1348465568    NONE: [plugin.video.watchmojo] ?action=Videos&url=%2fvideos%2f1
21:37:15.261 T:1348465568  NOTICE: [plugin.video.watchmojo] http://www.watchmojo.com/videos/1
21:37:15.261 T:1348465568    NONE: [plugin.video.watchmojo] UrlHash = 229487b84ee8a15bcf55050c910d8175
21:37:15.266 T:1348465568  NOTICE: [plugin.video.watchmojo] Cache Not Valid
21:37:16.822 T:1348465568    NONE: [plugin.video.watchmojo] 200 - OK
21:37:16.825 T:1348465568    NONE: [plugin.video.watchmojo] Character encoding: UTF-8
21:37:19.666 T:1348465568    NONE: [plugin.video.watchmojo] [3, 10, 32]
21:37:23.676 T:1340076960    NONE: [plugin.video.watchmojo] ?action=PlayVideo&videoid=18266&title=Ridley+Scott+to+Shoot+SIX+More+Alien+Movies+After+ALIEN%3A+COVENANT++The+CineFiles+Ep.+11
21:37:23.746 T:1340076960  NOTICE: [plugin.video.watchmojo] http://www.watchmojo.com/video/id/18266/
21:37:23.746 T:1340076960    NONE: [plugin.video.watchmojo] UrlHash = 340ef72cd74b286f684cc30e311881c7
21:37:23.750 T:1340076960    NONE: [plugin.video.watchmojo] Cache Not Found
21:37:29.884 T:1340076960    NONE: [plugin.video.watchmojo] 200 - OK
21:37:29.886 T:1340076960    NONE: [plugin.video.watchmojo] Character encoding: UTF-8
21:37:29.908 T:1340076960  SEVERE: [plugin.video.watchmojo] A Severe Unhandled Error was raise, unable to continue
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.xbmcutil/lib/xbmcutil/__init__.py", line 233, in wrapper
                                                try: response = function(*arguments, **keywords)
                                              File "/storage/.kodi/addons/plugin.video.watchmojo/resources/lib/main.py", line 71, in resolve
                                                return re.findall(search_str, sourceCode)[0]
                                            IndexError: list index out of range
21:37:29.927 T:1962197456   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.watchmojo/?action=PlayVideo&videoid=18266&title=Ridley+Scott+to+Shoot+SIX+More+Alien+Movies+After+ALIEN%3A+COVENANT++The+CineFiles+Ep.+11]
```

  Thanks,
               Ondra

**Comment by willforde** [comment]
Site changed again. I will push out an update later tonight.
This is good news cause now the add-on will be able to play HD videos.
Thanks for raising the issue.
